# file: nginx/tasks/modules/authorized_ips.yml

- name: Nginx | Modules | Updated the authorized_ip file
  template:
    src: modules/authorized_ips.j2
    dest: "{{nginx_dir}}/authorized_ips"
    owner: root
    group: root
    mode: 0644
