---

language: python
python: "2.7"
env:
  - INSTALL_METHOD=source
  - INSTALL_METHOD=package
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible==1.5.0
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --sudo -e "nginx_install_method=$INSTALL_METHOD"
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo -e "nginx_install_method=$INSTALL_METHOD"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
