# file: nginx/tasks/modules.yml

- include: modules/http_stub_status_module.yml
  when: nginx_source_modules_included.http_stub_status_module is defined

- include: modules/http_ssl_module.yml
  when: nginx_source_modules_included.http_ssl_module is defined

- include: modules/http_gzip_static_module.yml
  when: nginx_source_modules_included.http_gzip_static_module is defined

- include: modules/upload_progress_module.yml
  when: nginx_source_modules_included.upload_progress_module is defined

- include: modules/headers_more_module.yml
  when: nginx_source_modules_included.headers_more_module is defined

- include: modules/http_auth_request_module.yml
  when: nginx_source_modules_included.http_auth_request_module is defined

- include: modules/http_echo_module.yml
  when: nginx_source_modules_included.http_echo_module is defined

- include: modules/google_perftools_module.yml
  when: nginx_source_modules_included.google_perftools_module is defined

- include: modules/ipv6_module.yml
  when: nginx_source_modules_included.ipv6_module is defined

- include: modules/http_realip_module.yml
  when: nginx_source_modules_included.http_realip_module is defined

- include: modules/http_spdy_module.yml
  when: nginx_source_modules_included.http_spdy_module is defined

- include: modules/naxsi_module.yml
  when: nginx_source_modules_included.naxsi_module is defined

- include: modules/ngx_pagespeed.yml
  when: nginx_source_modules_included.ngx_pagespeed is defined
